config/routes.rb
Rails.application.routes.draw do
  root 'categories#show', id: 1
  resources :categories do
    collection do
      get :manage
      post :rebuild
    end
  end

  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  include TheSortableTree::Scopes
  acts_as_nested_set
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include TheSortableTreeController::Rebuild
 
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html do
          redirect_to @category, notice: 'Category was successfully created.'
        end

        format.json do
          render :show, status: :created, location: @category
        end
      else
        format.html { render :new }

        format.json do
          render json: @category.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html do
          redirect_to @category, notice: 'Category was successfully updated.'
        end

        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }

        format.json do
          render json: @category.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html do
        redirect_to categories_url,
                    notice: 'Category was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  def manage
    @categories = Category.nested_set.select('id, label, parent_id').all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list
    # through.
    def category_params
      params.require(:category).permit(:label, :parent_id, :lft, :rgt)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <% options = nested_set_options(Category) do |i|
    "#{'-' * i.level} #{i.label}"
    end %>
    <%= f.input :parent_id, collection: options %>
    <%= f.input :label %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/_submenu_pages.html.erb
<ul >
  <% pages.each do |page| %>
    <% if page == @category %>
      <li class="active">
    <% else %>
      <li>
    <% end %>
    <%= link_to_unless_current page.label, page %>

    <% if page.children.present? %>
      <%= render('submenu_pages', pages: page.children) %>
    <% end %>
      </li>
  <% end %>
</ul>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<ol class="sortable_tree" data-rebuild_url="<%= rebuild_categories_url %>">
  <%= sortable_tree @categories, title: :label %>
</ol>

<table>
  <thead>
    <tr>
      <th>Label</th>
      <th>Parent</th>
      <th>Lft</th>
      <th>Rgt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.label %></td>
        <td><%= category.parent_id %></td>
        <td><%= category.lft %></td>
        <td><%= category.rgt %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="containe-fluid">
    <div class="navbar-header">
      <%= link_to "Home", root_path, class: "navbar-brand" %>
    </div>
    <ul class="nav navbar-nav">
      <% Category.all.roots.each do |category| %>
        <% if @category.root == category %>
          <li class="active">
        <% else %>
          <li>
        <% end %>
        <%= link_to category.label, category %>
          </li>
      <% end %>
    </ul>
  </div>
</nav>

<div class="col-md-4">
  <%= render "submenu_pages", pages: @category.root.children %>
</div>

<% if false %>
<ol class="sortable_tree" data-rebuild_url="<%= rebuild_categories_url %>">
  <%= sortable_tree @categories, title: :label %>
</ol>
<% end %>

<div class="col-md-8">
  <ol class="breadcrumb">
    <% @category.ancestors.each do |category| %>
      <li>
        <%= link_to_unless_current category.label, category %>
      </li>
    <% end %>
    <li>
      <%= @category.label %>
    </li>
  </ol>

  <p id="notice"><%= notice %></p>

  <p>
    <strong>Label:</strong>
    <%= @category.label %>
  </p>

  <p>
    <strong>Parent:</strong>
    <%= @category.parent_id %>
  </p>

  <%= link_to 'Edit', edit_category_path(@category) %> |
  <%= link_to 'Back', categories_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
      <%= content_for?(:title) ? yield(:title) : "AwesomeNestedSetApp" %>
    </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag('apple-touch-icon-144x144-precomposed.png',
                         :rel => 'apple-touch-icon-precomposed',
                         :type => 'image/png', :sizes => '144x144') %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag('apple-touch-icon-114x114-precomposed.png',
                         :rel => 'apple-touch-icon-precomposed',
                         :type => 'image/png', :sizes => '114x114') %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag('apple-touch-icon-72x72-precomposed.png',
                         :rel => 'apple-touch-icon-precomposed',
                         :type => 'image/png', :sizes => '72x72') %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag('apple-touch-icon-precomposed.png',
                         :rel => 'apple-touch-icon-precomposed',
                         :type => 'image/png') %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"
      type="text/javascript">
      </script>
    <![endif]-->
  </head>

  <body>
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse"
                data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">AwesomeNestedSetApp</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>
    </div> <!-- /container -->
  </body>
</html>